CC = gcc
CFLAGS = -g -Wall

#ui_frame : ui_frame.c
#	$(CC) $(CFLAGS) -o ./ui_frame ./ui_frame.c -I../../inc/ui/ -L../../lib/ui/ -lui

ui_main : ui_main.c
	$(CC) $(CFLAGS) -o ./ui_main ./ui_main.c -lncurses
